project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - projects/**
    - resume/**

execute: 
  freeze: true

website:
  title: ""
  description: "Carter M. Smith's Personal Website"
  favicon: "/assets/images/hex-sticker.png"
  open-graph: true
  page-footer: 
    center: 
      © 2026 Carter M. Smith | Made with [Quarto](https://quarto.org)
  navbar:
    background: primary
    search: false
    left:
      - text: "About"
        href: /index.html
      - text: "Projects"
        href: /projects/
      - text: "Resume"
        href: /resume/carter-smith-august-2026-resume.pdf
        target: _blank
    tools:
      - icon: "github"
        menu:
        - text: Source
          href: https://github.com/cartermsmith/website.git
    collapse: true
    sidebar:
      logo: false

format:
  html:
    theme: brand.yml